const DATASET_SCHEMA = {
  billing_document_cancellations: {
    description: "Cancelled billing documents and linked accounting documents.",
    columns: [
      "accountingDocument",
      "billingDocument",
      "billingDocumentDate",
      "billingDocumentIsCancelled",
      "billingDocumentType",
      "cancelledBillingDocument",
      "companyCode",
      "creationDate",
      "creationTime",
      "fiscalYear",
      "lastChangeDateTime",
      "soldToParty",
      "totalNetAmount",
      "transactionCurrency",
    ],
  },
  billing_document_headers: {
    description: "Billing document headers for invoices and credit memo documents.",
    columns: [
      "accountingDocument",
      "billingDocument",
      "billingDocumentDate",
      "billingDocumentIsCancelled",
      "billingDocumentType",
      "cancelledBillingDocument",
      "companyCode",
      "creationDate",
      "creationTime",
      "fiscalYear",
      "lastChangeDateTime",
      "soldToParty",
      "totalNetAmount",
      "transactionCurrency",
    ],
  },
  billing_document_items: {
    description: "Billing line items with references back to deliveries.",
    columns: [
      "billingDocument",
      "billingDocumentItem",
      "billingQuantity",
      "billingQuantityUnit",
      "material",
      "netAmount",
      "referenceSdDocument",
      "referenceSdDocumentItem",
      "transactionCurrency",
    ],
  },
  business_partner_addresses: {
    description: "Address master data for business partners.",
    columns: [
      "addressId",
      "addressTimeZone",
      "addressUuid",
      "businessPartner",
      "cityName",
      "country",
      "poBox",
      "poBoxDeviatingCityName",
      "poBoxDeviatingCountry",
      "poBoxDeviatingRegion",
      "poBoxIsWithoutNumber",
      "poBoxLobbyName",
      "poBoxPostalCode",
      "postalCode",
      "region",
      "streetName",
      "taxJurisdiction",
      "transportZone",
      "validityEndDate",
      "validityStartDate",
    ],
  },
  business_partners: {
    description: "Business partner and customer master data.",
    columns: [
      "businessPartner",
      "businessPartnerCategory",
      "businessPartnerFullName",
      "businessPartnerGrouping",
      "businessPartnerIsBlocked",
      "businessPartnerName",
      "correspondenceLanguage",
      "createdByUser",
      "creationDate",
      "creationTime",
      "customer",
      "firstName",
      "formOfAddress",
      "industry",
      "isMarkedForArchiving",
      "lastChangeDate",
      "lastName",
      "organizationBpName1",
      "organizationBpName2",
    ],
  },
  customer_company_assignments: {
    description: "Customer attributes in company code scope.",
    columns: [
      "accountingClerk",
      "accountingClerkFaxNumber",
      "accountingClerkInternetAddress",
      "accountingClerkPhoneNumber",
      "alternativePayerAccount",
      "companyCode",
      "customer",
      "customerAccountGroup",
      "deletionIndicator",
      "paymentBlockingReason",
      "paymentMethodsList",
      "paymentTerms",
      "reconciliationAccount",
    ],
  },
  customer_sales_area_assignments: {
    description: "Customer data in sales area scope.",
    columns: [
      "billingIsBlockedForCustomer",
      "completeDeliveryIsDefined",
      "creditControlArea",
      "currency",
      "customer",
      "customerPaymentTerms",
      "deliveryPriority",
      "distributionChannel",
      "division",
      "exchangeRateType",
      "incotermsClassification",
      "incotermsLocation1",
      "salesDistrict",
      "salesGroup",
      "salesOffice",
      "salesOrganization",
      "shippingCondition",
      "slsUnlmtdOvrdelivIsAllwd",
      "supplyingPlant",
    ],
  },
  journal_entry_items_accounts_receivable: {
    description: "Accounts receivable journal entry lines tied to billing documents.",
    columns: [
      "accountingDocument",
      "accountingDocumentItem",
      "accountingDocumentType",
      "amountInCompanyCodeCurrency",
      "amountInTransactionCurrency",
      "assignmentReference",
      "clearingAccountingDocument",
      "clearingDate",
      "clearingDocFiscalYear",
      "companyCode",
      "companyCodeCurrency",
      "costCenter",
      "customer",
      "documentDate",
      "financialAccountType",
      "fiscalYear",
      "glAccount",
      "lastChangeDateTime",
      "postingDate",
      "profitCenter",
      "referenceDocument",
      "transactionCurrency",
    ],
  },
  outbound_delivery_headers: {
    description: "Outbound delivery header records.",
    columns: [
      "actualGoodsMovementDate",
      "actualGoodsMovementTime",
      "creationDate",
      "creationTime",
      "deliveryBlockReason",
      "deliveryDocument",
      "hdrGeneralIncompletionStatus",
      "headerBillingBlockReason",
      "lastChangeDate",
      "overallGoodsMovementStatus",
      "overallPickingStatus",
      "overallProofOfDeliveryStatus",
      "shippingPoint",
    ],
  },
  outbound_delivery_items: {
    description: "Outbound delivery line items linked back to sales orders.",
    columns: [
      "actualDeliveryQuantity",
      "batch",
      "deliveryDocument",
      "deliveryDocumentItem",
      "deliveryQuantityUnit",
      "itemBillingBlockReason",
      "lastChangeDate",
      "plant",
      "referenceSdDocument",
      "referenceSdDocumentItem",
      "storageLocation",
    ],
  },
  payments_accounts_receivable: {
    description: "Payment and clearing records for accounts receivable.",
    columns: [
      "accountingDocument",
      "accountingDocumentItem",
      "amountInCompanyCodeCurrency",
      "amountInTransactionCurrency",
      "assignmentReference",
      "clearingAccountingDocument",
      "clearingDate",
      "clearingDocFiscalYear",
      "companyCode",
      "companyCodeCurrency",
      "costCenter",
      "customer",
      "documentDate",
      "financialAccountType",
      "fiscalYear",
      "glAccount",
      "invoiceReference",
      "invoiceReferenceFiscalYear",
      "postingDate",
      "profitCenter",
      "salesDocument",
      "salesDocumentItem",
      "transactionCurrency",
    ],
  },
  plants: {
    description: "Plant master data.",
    columns: [
      "addressId",
      "defaultPurchasingOrganization",
      "distributionChannel",
      "division",
      "factoryCalendar",
      "isMarkedForArchiving",
      "language",
      "plant",
      "plantCategory",
      "plantCustomer",
      "plantName",
      "plantSupplier",
      "salesOrganization",
      "valuationArea",
    ],
  },
  product_descriptions: {
    description: "Product descriptions by language.",
    columns: ["language", "product", "productDescription"],
  },
  product_plants: {
    description: "Product master data in plant scope.",
    columns: [
      "availabilityCheckType",
      "countryOfOrigin",
      "fiscalYearVariant",
      "mrpType",
      "plant",
      "product",
      "productionInvtryManagedLoc",
      "profitCenter",
      "regionOfOrigin",
    ],
  },
  product_storage_locations: {
    description: "Product stock data by plant and storage location.",
    columns: [
      "dateOfLastPostedCntUnRstrcdStk",
      "physicalInventoryBlockInd",
      "plant",
      "product",
      "storageLocation",
    ],
  },
  products: {
    description: "Product master records.",
    columns: [
      "baseUnit",
      "createdByUser",
      "creationDate",
      "crossPlantStatus",
      "crossPlantStatusValidityDate",
      "division",
      "grossWeight",
      "industrySector",
      "isMarkedForDeletion",
      "lastChangeDate",
      "lastChangeDateTime",
      "netWeight",
      "product",
      "productGroup",
      "productOldId",
      "productType",
      "weightUnit",
    ],
  },
  sales_order_headers: {
    description: "Sales order header data.",
    columns: [
      "createdByUser",
      "creationDate",
      "customerPaymentTerms",
      "deliveryBlockReason",
      "distributionChannel",
      "headerBillingBlockReason",
      "incotermsClassification",
      "incotermsLocation1",
      "lastChangeDateTime",
      "organizationDivision",
      "overallDeliveryStatus",
      "overallOrdReltdBillgStatus",
      "overallSdDocReferenceStatus",
      "pricingDate",
      "requestedDeliveryDate",
      "salesGroup",
      "salesOffice",
      "salesOrder",
      "salesOrderType",
      "salesOrganization",
      "soldToParty",
      "totalCreditCheckStatus",
      "totalNetAmount",
      "transactionCurrency",
    ],
  },
  sales_order_items: {
    description: "Sales order line items.",
    columns: [
      "itemBillingBlockReason",
      "material",
      "materialGroup",
      "netAmount",
      "productionPlant",
      "requestedQuantity",
      "requestedQuantityUnit",
      "salesDocumentRjcnReason",
      "salesOrder",
      "salesOrderItem",
      "salesOrderItemCategory",
      "storageLocation",
      "transactionCurrency",
    ],
  },
  sales_order_schedule_lines: {
    description: "Schedule line commitments for sales order items.",
    columns: [
      "confdOrderQtyByMatlAvailCheck",
      "confirmedDeliveryDate",
      "orderQuantityUnit",
      "salesOrder",
      "salesOrderItem",
      "scheduleLine",
    ],
  },
};

const INDEX_DEFINITIONS = [
  ["sales_order_headers", ["salesOrder"]],
  ["sales_order_headers", ["soldToParty"]],
  ["sales_order_items", ["salesOrder"]],
  ["sales_order_items", ["material"]],
  ["sales_order_schedule_lines", ["salesOrder", "salesOrderItem"]],
  ["outbound_delivery_headers", ["deliveryDocument"]],
  ["outbound_delivery_items", ["deliveryDocument"]],
  ["outbound_delivery_items", ["referenceSdDocument"]],
  ["billing_document_headers", ["billingDocument"]],
  ["billing_document_headers", ["accountingDocument"]],
  ["billing_document_items", ["billingDocument"]],
  ["billing_document_items", ["referenceSdDocument"]],
  ["journal_entry_items_accounts_receivable", ["accountingDocument"]],
  ["journal_entry_items_accounts_receivable", ["referenceDocument"]],
  ["journal_entry_items_accounts_receivable", ["clearingAccountingDocument"]],
  ["payments_accounts_receivable", ["clearingAccountingDocument"]],
  ["payments_accounts_receivable", ["accountingDocument"]],
  ["payments_accounts_receivable", ["invoiceReference"]],
  ["payments_accounts_receivable", ["salesDocument"]],
  ["business_partners", ["customer"]],
  ["customer_company_assignments", ["customer", "companyCode"]],
  ["customer_sales_area_assignments", ["customer", "salesOrganization"]],
  ["products", ["product"]],
  ["product_descriptions", ["product"]],
  ["product_plants", ["product", "plant"]],
  ["product_storage_locations", ["product", "plant"]],
];

const ENTITY_ALIASES = {
  business_partner: [
    "business partner",
    "business_partner",
    "partner",
    "customer master",
    "customer",
  ],
  business_partner_address: [
    "business partner address",
    "business_partner_address",
    "partner address",
    "address",
  ],
  customer_company_assignment: [
    "customer company assignment",
    "customer_company_assignment",
    "customer company",
    "company assignment",
  ],
  customer_sales_area_assignment: [
    "customer sales area assignment",
    "customer_sales_area_assignment",
    "customer sales area",
    "sales area assignment",
  ],
  sales_order: [
    "sales order",
    "sales_order",
    "salesorder",
    "order",
    "orders",
  ],
  sales_order_item: [
    "sales order item",
    "sales_order_item",
    "order item",
    "line item",
  ],
  sales_order_schedule_line: [
    "sales order schedule line",
    "sales_order_schedule_line",
    "schedule line",
  ],
  delivery: [
    "delivery",
    "deliveries",
    "outbound delivery",
    "outbound_delivery",
    "shipment",
    "shipments",
  ],
  delivery_item: [
    "delivery item",
    "delivery_item",
    "outbound delivery item",
  ],
  billing: [
    "billing",
    "billing document",
    "billing_document",
    "invoice",
    "invoices",
  ],
  billing_item: [
    "billing item",
    "billing_item",
    "invoice item",
  ],
  billing_cancellation: [
    "billing cancellation",
    "billing_cancellation",
    "cancelled billing",
    "cancelled invoice",
    "invoice cancellation",
  ],
  accounting: [
    "accounting",
    "accounting document",
    "accounting_document",
    "journal",
    "journal entry",
    "receivable",
    "ar",
  ],
  payment: ["payment", "payments", "receipt", "receipts", "clearing document"],
  product: ["product", "products", "material", "materials", "sku"],
  product_description: [
    "product description",
    "product_description",
    "material description",
  ],
  product_plant: [
    "product plant",
    "product_plant",
    "material plant",
  ],
  product_storage_location: [
    "product storage location",
    "product_storage_location",
    "storage location",
    "material storage",
  ],
  plant: ["plant", "plants", "warehouse", "location"],
};

const DOMAIN_KEYWORDS = [
  "sales order",
  "sales order item",
  "schedule line",
  "order",
  "delivery",
  "delivery item",
  "shipment",
  "billing",
  "billing item",
  "billing cancellation",
  "invoice",
  "accounting",
  "journal",
  "payment",
  "customer",
  "business partner",
  "address",
  "product",
  "material",
  "plant",
  "storage location",
  "company code",
  "sales area",
  "sales organization",
  "distribution channel",
  "currency",
  "amount",
  "quantity",
  "receivable",
  "billing document",
  "delivery document",
  "accounting document",
  "sold to party",
  "reference document",
];

const GRAPH_ENTITY_TEST_INPUT = {
  entity: "billing",
  id: "90504204",
};

module.exports = {
  DATASET_SCHEMA,
  DOMAIN_KEYWORDS,
  ENTITY_ALIASES,
  GRAPH_ENTITY_TEST_INPUT,
  INDEX_DEFINITIONS,
};
